version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: quant-drl-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 10s

  web:
    image: "ghcr.io/pablodieaco/quant-drl-web:latest" 
    container_name: quant-drl-web
    profiles: ["remote"]
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    volumes:
      - .:/app 
      - ./examples:/app/examples
    working_dir: /app
    command: >
      bash -c "
        python web/db/create_tables.py &&
        python web/db/upload_companies.py &&
        python web/db/upload_models_data.py &&
        python web/db/upload_evaluation_data.py &&
        streamlit run web/app.py --server.port=8501 --server.enableCORS=false
      "
  
  web-develop:
    image: "ghcr.io/pablodieaco/quant-drl-web-develop:latest" 
    container_name: quant-drl-web-develop
    profiles: ["develop"]
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8502:8501"
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    volumes:
      - .:/app 
      - ./examples:/app/examples
    working_dir: /app
    command: >
      bash -c "
        python web/db/create_tables.py &&
        python web/db/upload_companies.py &&
        python web/db/upload_models_data.py &&
        python web/db/upload_evaluation_data.py &&
        streamlit run web/app.py --server.port=8501 --server.enableCORS=false
      "
  web-local:
    build:
        context: .
        dockerfile: Dockerfile

    image: "quant-drl-web:latest" 
    container_name: quant-drl-web-local
    profiles: ["local"] 
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    volumes:
      - .:/app
      - ./examples:/app/examples
    working_dir: /app
    command: >
      bash -c "
        python web/db/create_tables.py &&
        python web/db/upload_companies.py &&
        python web/db/upload_models_data.py &&
        python web/db/upload_evaluation_data.py &&
        streamlit run web/app.py --server.port=8501 --server.enableCORS=false
      "
volumes:
  postgres_data:
    driver: local
